Add linear regression
vaskers5/Educational_Nets pull request #2
Opened 2021-10-11 12:20 UTC by vaskers5

2021-10-11 17:15 UTC, ARQtty commented on lib/models/__init__.py
> +from .linear_regression import LinearRegression
newline

2021-10-11 17:15 UTC, ARQtty commented on lib/models/linear_regression.py
> +        self.weights = np.array([])
зачем пустой?

2021-10-11 17:16 UTC, ARQtty commented on lib/models/linear_regression.py
> +        self.losses = []
и все эти переменные public. Зачем?

2021-10-11 17:16 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def train(self, features: np.ndarray,
все аргументы нужно писать либо в одной строке, либо в одном столбце

2021-10-11 17:17 UTC, ARQtty commented on lib/models/linear_regression.py
> +        self.weights = np.random.rand(features.shape[1])
рандом с незафиксированным сидом? Это невоспроизводимый код

2021-10-11 17:18 UTC, ARQtty commented on lib/models/linear_regression.py
> +            old_weights = self.weights.copy()
здесь создаётся переменная, которая может в итоге не быть использована. Зачем?

2021-10-11 17:18 UTC, ARQtty commented on lib/models/linear_regression.py
> +            self.losses += [loss]
.append

2021-10-11 17:18 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def load_weights(self, path_to_weights: str) -> None:
path должен быть типом Path

2021-10-11 17:19 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def load_weights(self, path_to_weights: str) -> None:
Если ты такой любитель возвращать LinearRegression, то почему здесь None?

2021-10-11 17:19 UTC, ARQtty commented on lib/models/linear_regression.py
> +            last_version = yaml.load(f)
веса в yaml это точно ок?

2021-10-11 17:20 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def save_weights(self, path_to_weights: str) -> None:
path

2021-10-11 17:20 UTC, ARQtty commented on lib/models/linear_regression.py
> +        return np.dot(features, self.weights)
всегда ли у фичей есть дополнительная колонка единиц? Кажется, код может крашиться, если не делать дополнительную предобработку данных

2021-10-11 17:21 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def mse_loss(predict: np.array, labels: np.array) -> float:
ndarray

2021-10-11 18:31 UTC, vaskers5 commented on lib/models/__init__.py
> +from .linear_regression import LinearRegression
fixed

2021-10-11 18:40 UTC, vaskers5 commented on lib/models/linear_regression.py
> +    def train(self, features: np.ndarray,
fixed

2021-10-11 18:52 UTC, vaskers5 commented on lib/models/linear_regression.py
> +            last_version = yaml.load(f)
fixed

2021-10-17 16:24 UTC, ARQtty requested changes
зачем файл .gitattributes?

2021-10-17 16:24 UTC, ARQtty commented on lib/models/linear_regression.py
> +np.random.seed(0)
хорошей ли идеей является создания сида в самом модуле? Получается сид будет сажаться при импорте модуля. А значит два разных запуска модели будут по-разному инициалированы. Получается, этот сид бесполезен

2021-10-17 16:24 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def train(self, features: np.ndarray,
![image](https://user-images.githubusercontent.com/22442872/137635989-6f7ac13c-b9d8-43a1-b31f-28f3980fb5e6.png)
Нет

2021-10-17 16:24 UTC, ARQtty commented on lib/models/linear_regression.py
> +    def get_loss(self) -> List[float]:
get_loss подразумевает одно число - loss. Ты возвращаешь множество лоссов - losses. Путаница

2021-10-17 16:24 UTC, ARQtty commented on lib/models/linear_regression.py
> +        return np.c_[features, np.ones(features.shape[0])]
newline

2021-10-30 21:02 UTC, ARQtty commented
хеллоу?

2021-10-31 15:45 UTC, vaskers5 commented on lib/models/linear_regression.py
> +        return np.c_[features, np.ones(features.shape[0])]
fixed

2021-10-31 15:46 UTC, vaskers5 commented on lib/models/linear_regression.py
> +    def get_loss(self) -> List[float]:
fixed

2021-10-31 15:50 UTC, vaskers5 commented on lib/models/linear_regression.py
> +np.random.seed(0)
fixed

2021-11-01 11:13 UTC, ARQtty approved these changes
great

2021-11-01 22:35 UTC, merged